data:
  raw_path: "./data/crunchbase/"
  processed_path: "./data/processed/"

model:
  embedding_dim: 40
  recurrent_layers: 2
  attention_heads: 4

training:
  batch_size: 512
  learning_rate: 0.001
  epochs: 30
  segment_length: 3  # Time span for trend segments in months

doc2vec:
  vector_size: 300
  window: 5
  min_count: 1
  workers: 4
  epochs: 40

output:
  model_dir: "./saved_models/"
  result_dir: "./results/"



trend_extractor:
  input_dim: 40
  hidden_dim: 40
  num_layers: 2
  output_dim: 20
  epochs: 5
  structure: [40, 80, 160]

trend_extractor_alternate:
  input_dim: 40
  hidden_dim: 40
  num_layers: 2
  output_dim: 20
  epochs: 10
  structure: [40, 160, 320]

trend_extractor_deep:
  input_dim: 40
  attention_dim: 40  # Make sure this matches input_dim if needed
  hidden_dim: 80
  num_layers: 3
  output_dim: 20
  epochs: 15
  structure: [80, 160, 320, 640]

